version: '3.7' 
services: 
    angular-service: 
      container_name: tic-tac-toe-frontend 
      build: 
        context: .
        dockerfile: Dockerfile
      volumes: 
        - '.:/app' 
        - '/app/node_modules'
      ports: 
        - '4200:4200' # Port mapping